# Generated by Django 5.2.1 on 2025-12-11 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('duration_days', models.PositiveIntegerField(default=0)),
                ('duration_nights', models.PositiveIntegerField(default=0)),
                ('spots_count', models.PositiveIntegerField(default=0)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('summary_itinerary', models.JSONField(blank=True, default=list)),
                ('view_details', models.BooleanField(default=True)),
                ('share', models.BooleanField(default=True)),
                ('save', models.BooleanField(default=True)),
                ('regenerate_plan', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
