# Generated by Django 5.2.1 on 2025-12-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_saved',
            field=models.BooleanField(default=True),
        ),
    ]
