# Generated by Django 5.2.1 on 2025-12-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_trip_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='save',
        ),
    ]
