# Generated by Django 5.2.1 on 2025-12-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_trip_location_alter_trip_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
