# Generated by Django 5.2.1 on 2025-12-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
