# Generated by Django 5.2.1 on 2025-12-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
