# Generated by Django 5.2.1 on 2025-12-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_shared',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
