# Generated by Django 5.2.1 on 2025-12-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_trip_is_shared'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='post',
            name='is_shared',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
