# Generated by Django 5.2.1 on 2025-12-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_alter_post_options_alter_trip_options_post_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
