# Generated by Django 5.2.1 on 2025-12-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_post_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
