# Generated by Django 5.2.1 on 2026-02-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_usage',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
