# Generated by Django 5.2.1 on 2026-03-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_card_usage_user_trial_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_usage',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
