# Generated by Django 5.2.1 on 2026-03-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_card_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_usage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
